worldMap = document.getElementById("map");

let countriesData = [
  ["World", 2021, 100.0, 37123.852],
  ["Asia", 2021, 58.421, 21688.25],
  ["Upper-middle-income countries", 2021, 45.897, 17038.822],
  ["High-income countries", 2021, 33.715, 12516.404],
  ["China", 2021, 30.903, 11472.368],
  ["Asia (excl. China and India)", 2021, 20.219, 7506.198],
  ["Lower-middle-income countries", 2021, 16.859, 6258.658],
  ["North America", 2021, 16.534, 6137.9],
  ["Europe", 2021, 14.293, 5306.228],
  ["United States", 2021, 13.488, 5007.336],
  ["European Union (28)", 2021, 8.458, 3139.79],
  ["European Union (27)", 2021, 7.524, 2793.016],
  ["India", 2021, 7.299, 2709.684],
  ["Europe (excl. EU-27)", 2021, 6.77, 2513.211],
  ["Europe (excl. EU-28)", 2021, 5.836, 2166.438],
  ["Russia", 2021, 4.729, 1755.547],
  ["Africa", 2021, 3.908, 1450.796],
  ["North America (excl. USA)", 2021, 3.045, 1130.564],
  ["South America", 2021, 2.896, 1074.999],
  ["Japan", 2021, 2.875, 1067.398],
  ["International transport", 2021, 2.752, 1021.749],
  ["Iran", 2021, 2.017, 748.879],
  ["Germany", 2021, 1.818, 674.754],
  ["Saudi Arabia", 2021, 1.811, 672.38],
  ["Indonesia", 2021, 1.668, 619.278],
  ["South Korea", 2021, 1.66, 616.075],
  ["Canada", 2021, 1.47, 545.635],
  ["Brazil", 2021, 1.317, 488.881],
  ["Turkey", 2021, 1.202, 446.204],
  ["Oceania", 2021, 1.194, 443.192],
  ["South Africa", 2021, 1.174, 435.929],
  ["Mexico", 2021, 1.097, 407.205],
  ["Australia", 2021, 1.054, 391.187],
  ["United Kingdom", 2021, 0.934, 346.773],
  ["Italy", 2021, 0.885, 328.687],
  ["Poland", 2021, 0.885, 328.58],
  ["Vietnam", 2021, 0.878, 326.014],
  ["France", 2021, 0.824, 305.964],
  ["Taiwan", 2021, 0.762, 282.856],
  ["Thailand", 2021, 0.75, 278.496],
  ["Kazakhstan", 2021, 0.745, 276.683],
  ["Malaysia", 2021, 0.69, 256.049],
  ["Egypt", 2021, 0.672, 249.624],
  ["Spain", 2021, 0.629, 233.65],
  ["Pakistan", 2021, 0.618, 229.512],
  ["United Arab Emirates", 2021, 0.55, 204.087],
  ["Ukraine", 2021, 0.544, 201.858],
  ["Low-income countries", 2021, 0.535, 198.783],
  ["Argentina", 2021, 0.502, 186.448],
  ["Iraq", 2021, 0.5, 185.581],
  ["Algeria", 2021, 0.475, 176.269],
  ["Philippines", 2021, 0.389, 144.264],
  ["Netherlands", 2021, 0.38, 141.045],
  ["Nigeria", 2021, 0.369, 136.987],
  ["Uzbekistan", 2021, 0.328, 121.631],
  ["Kuwait", 2021, 0.286, 106.134],
  ["Czechia", 2021, 0.262, 97.138],
  ["Belgium", 2021, 0.258, 95.722],
  ["Qatar", 2021, 0.258, 95.667],
  ["Bangladesh", 2021, 0.251, 93.176],
  ["Colombia", 2021, 0.247, 91.703],
  ["Chile", 2021, 0.23, 85.447],
  ["Turkmenistan", 2021, 0.224, 83.007],
  ["Oman", 2021, 0.218, 80.991],
  ["Venezuela", 2021, 0.215, 79.747],
  ["Romania", 2021, 0.214, 79.327],
  ["Libya", 2021, 0.201, 74.525],
  ["Morocco", 2021, 0.19, 70.578],
  ["Austria", 2021, 0.174, 64.626],
  ["Belarus", 2021, 0.161, 59.602],
  ["Greece", 2021, 0.152, 56.309],
  ["North Korea", 2021, 0.152, 56.38],
  ["Peru", 2021, 0.152, 56.282],
  ["Israel", 2021, 0.147, 54.529],
  ["Mongolia", 2021, 0.136, 50.316],
  ["Hungary", 2021, 0.131, 48.455],
  ["Bulgaria", 2021, 0.115, 42.56],
  ["Ecuador", 2021, 0.111, 41.322],
  ["Norway", 2021, 0.11, 40.919],
  ["Portugal", 2021, 0.11, 40.797],
  ["Bahrain", 2021, 0.105, 39.016],
  ["Azerbaijan", 2021, 0.104, 38.493],
  ["Finland", 2021, 0.101, 37.602],
  ["Ireland", 2021, 0.101, 37.54],
  ["Myanmar", 2021, 0.098, 36.307],
  ["Sweden", 2021, 0.097, 35.849],
  ["Trinidad and Tobago", 2021, 0.097, 36.124],
  ["Slovakia", 2021, 0.095, 35.308],
  ["Switzerland", 2021, 0.094, 34.932],
  ["New Zealand", 2021, 0.091, 33.79],
  ["Singapore", 2021, 0.088, 32.507],
  ["Hong Kong", 2021, 0.085, 31.664],
  ["Tunisia", 2021, 0.085, 31.583],
  ["Serbia", 2021, 0.083, 30.869],
  ["Denmark", 2021, 0.08, 29.577],
  ["Dominican Republic", 2021, 0.078, 28.922],
  ["Syria", 2021, 0.073, 27.001],
  ["Jordan", 2021, 0.069, 25.594],
  ["Lebanon", 2021, 0.067, 24.959],
  ["Bolivia", 2021, 0.063, 23.322],
  ["Cuba", 2021, 0.059, 22.057],
  ["Angola", 2021, 0.058, 21.363],
  ["Ghana", 2021, 0.057, 21.313],
  ["Sudan", 2021, 0.057, 21.038],
  ["Laos", 2021, 0.056, 20.778],
  ["Sri Lanka", 2021, 0.056, 20.781],
  ["Guatemala", 2021, 0.055, 20.327],
  ["Kenya", 2021, 0.054, 19.875],
  ["Cambodia", 2021, 0.051, 19.029],
  ["Croatia", 2021, 0.048, 17.701],
  ["Ethiopia", 2021, 0.048, 17.793],
  ["Nepal", 2021, 0.038, 14.173],
  ["Bosnia and Herzegovina", 2021, 0.037, 13.566],
  ["Lithuania", 2021, 0.037, 13.881],
  ["Senegal", 2021, 0.037, 13.598],
  ["Panama", 2021, 0.035, 13.032],
  ["Tanzania", 2021, 0.035, 13.059],
  ["Slovenia", 2021, 0.034, 12.549],
  ["Yemen", 2021, 0.034, 12.477],
  ["Afghanistan", 2021, 0.032, 11.874],
  ["Cote d'Ivoire", 2021, 0.032, 11.707],
  ["Georgia", 2021, 0.03, 11.01],
  ["Zimbabwe", 2021, 0.03, 11.296],
  ["Honduras", 2021, 0.029, 10.898],
  ["Brunei", 2021, 0.028, 10.481],
  ["Estonia", 2021, 0.028, 10.449],
  ["Tajikistan", 2021, 0.028, 10.336],
  ["Cameroon", 2021, 0.025, 9.297],
  ["Kyrgyzstan", 2021, 0.025, 9.308],
  ["Luxembourg", 2021, 0.023, 8.355],
  ["Papua New Guinea", 2021, 0.023, 8.51],
  ["Paraguay", 2021, 0.023, 8.577],
  ["Benin", 2021, 0.021, 7.756],
  ["Costa Rica", 2021, 0.021, 7.82],
  ["Jamaica", 2021, 0.021, 7.69],
  ["Zambia", 2021, 0.021, 7.676],
  ["Congo", 2021, 0.02, 7.464],
  ["Cyprus", 2021, 0.02, 7.6],
  ["Latvia", 2021, 0.02, 7.266],
  ["El Salvador", 2021, 0.019, 7.204],
  ["Mozambique", 2021, 0.019, 7.156],
  ["Armenia", 2021, 0.018, 6.806],
  ["Botswana", 2021, 0.018, 6.5],
  ["North Macedonia", 2021, 0.018, 6.852],
  ["Uruguay", 2021, 0.018, 6.738],
  ["Uganda", 2021, 0.016, 5.78],
  ["Burkina Faso", 2021, 0.015, 5.698],
  ["Gabon", 2021, 0.015, 5.712],
  ["Kosovo", 2021, 0.015, 5.644],
  ["Moldova", 2021, 0.015, 5.602],
  ["New Caledonia", 2021, 0.015, 5.496],
  ["Equatorial Guinea", 2021, 0.014, 5.225],
  ["Nicaragua", 2021, 0.014, 5.06],
  ["Guinea", 2021, 0.013, 4.842],
  ["Albania", 2021, 0.012, 4.619],
  ["Mauritius", 2021, 0.012, 4.472],
  ["Madagascar", 2021, 0.011, 4.244],
  ["Mali", 2021, 0.011, 4.17],
  ["Mauritania", 2021, 0.011, 4.118],
  ["Namibia", 2021, 0.011, 4.015],
  ["Reunion", 2021, 0.011, 4.103],
  ["Iceland", 2021, 0.009, 3.375],
  ["Guyana", 2021, 0.008, 3.088],
  ["Haiti", 2021, 0.008, 2.876],
  ["Palestine", 2021, 0.008, 3.092],
  ["Suriname", 2021, 0.008, 2.793],
  ["Democratic Republic of Congo", 2021, 0.007, 2.607],
  ["Niger", 2021, 0.007, 2.699],
  ["Bahamas", 2021, 0.006, 2.386],
  ["Guadeloupe", 2021, 0.006, 2.291],
  ["Lesotho", 2021, 0.006, 2.282],
  ["Maldives", 2021, 0.006, 2.118],
  ["Martinique", 2021, 0.006, 2.1],
  ["Togo", 2021, 0.006, 2.342],
  ["Chad", 2021, 0.005, 1.94],
  ["Curacao", 2021, 0.005, 1.844],
  ["Malta", 2021, 0.005, 1.724],
  ["Montenegro", 2021, 0.005, 1.751],
  ["Rwanda", 2021, 0.005, 1.755],
  ["Bhutan", 2021, 0.004, 1.522],
  ["Fiji", 2021, 0.004, 1.47],
  ["Malawi", 2021, 0.004, 1.552],
  ["Sierra Leone", 2021, 0.004, 1.299],
  ["South Sudan", 2021, 0.004, 1.582],
  ["Barbados", 2021, 0.003, 1.125],
  ["Eswatini", 2021, 0.003, 1.087],
  ["French Polynesia", 2021, 0.003, 0.95],
  ["Liberia", 2021, 0.003, 1.195],
  ["Macao", 2021, 0.003, 1.287],
  ["Aruba", 2021, 0.002, 0.858],
  ["Belize", 2021, 0.002, 0.689],
  ["Burundi", 2021, 0.002, 0.693],
  ["Cape Verde", 2021, 0.002, 0.668],
  ["Eritrea", 2021, 0.002, 0.821],
  ["Faeroe Islands", 2021, 0.002, 0.698],
  ["French Guiana", 2021, 0.002, 0.651],
  ["Gambia", 2021, 0.002, 0.656],
  ["Seychelles", 2021, 0.002, 0.568],
  ["Sint Maarten (Dutch part)", 2021, 0.002, 0.648],
  ["Somalia", 2021, 0.002, 0.61],
  ["Timor", 2021, 0.002, 0.736],
  ["Andorra", 2021, 0.001, 0.453],
  ["Antigua and Barbuda", 2021, 0.001, 0.469],
  ["Bermuda", 2021, 0.001, 0.548],
  ["Central African Republic", 2021, 0.001, 0.227],
  ["Comoros", 2021, 0.001, 0.298],
  ["Djibouti", 2021, 0.001, 0.379],
  ["Greenland", 2021, 0.001, 0.511],
  ["Grenada", 2021, 0.001, 0.319],
  ["Guinea-Bissau", 2021, 0.001, 0.352],
  ["Mayotte", 2021, 0.001, 0.273],
  ["Palau", 2021, 0.001, 0.238],
  ["Saint Kitts and Nevis", 2021, 0.001, 0.238],
  ["Saint Lucia", 2021, 0.001, 0.486],
  ["Saint Vincent and the Grenadines", 2021, 0.001, 0.214],
  ["Samoa", 2021, 0.001, 0.294],
  ["Solomon Islands", 2021, 0.001, 0.318],
  ["Turks and Caicos Islands", 2021, 0.001, 0.341],
  ["Anguilla", 2021, 0.0, 0.145],
  ["Bonaire Sint Eustatius and Saba", 2021, 0.0, 0.103],
  ["British Virgin Islands", 2021, 0.0, 0.159],
  ["Cook Islands", 2021, 0.0, 0.091],
  ["Dominica", 2021, 0.0, 0.159],
  ["Kiribati", 2021, 0.0, 0.072],
  ["Liechtenstein", 2021, 0.0, 0.151],
  ["Marshall Islands", 2021, 0.0, 0.159],
  ["Micronesia (country)", 2021, 0.0, 0.159],
  ["Montserrat", 2021, 0.0, 0.021],
  ["Nauru", 2021, 0.0, 0.06],
  ["Niue", 2021, 0.0, 0.012],
  ["Saint Helena", 2021, 0.0, 0.014],
  ["Saint Pierre and Miquelon", 2021, 0.0, 0.062],
  ["Sao Tome and Principe", 2021, 0.0, 0.132],
  ["Tonga", 2021, 0.0, 0.175],
  ["Tuvalu", 2021, 0.0, 0.008],
  ["Vanuatu", 2021, 0.0, 0.175],
  ["Wallis and Futuna", 2021, 0.0, 0.028],
  ["Africa (GCP)", 2021, 0, 1450.783],
  ["Aland Islands", 2021, 0, 0],
  ["American Samoa", 2021, 0, 0],
  ["Antarctica", 2021, 0, 0],
  ["Asia (GCP)", 2021, 0, 18970.906],
  ["Central America (GCP)", 2021, 0, 177.165],
  ["Christmas Island", 2021, 0, 0],
  ["Europe (GCP)", 2021, 0, 5306.228],
  ["European Union (27) (GCP)", 2021, 0, 2793.016],
  ["Falkland Islands", 2021, 0, 0],
  ["French Equatorial Africa (Jones et al. 2023)", 2021, 0, 0],
  ["French West Africa (Jones et al. 2023)", 2021, 0, 0],
  ["Guernsey", 2021, 0, 0],
  ["Isle of Man", 2021, 0, 0],
  ["Jersey", 2021, 0, 0],
  ["Kuwaiti Oil Fires (Jones et al. 2023)", 2021, 0, 0],
  ["Least developed countries (Jones et al. 2023)", 2021, 0, 0],
  ["Leeward Islands (Jones et al. 2023)", 2021, 0, 0],
  ["Middle East (GCP)", 2021, 0, 2726.59],
  ["Netherlands Antilles", 2021, 0, 0],
  ["Non-OECD (GCP)", 2021, 0, 24398.34],
  ["North America (GCP)", 2021, 0, 5960.749],
  ["OECD (GCP)", 2021, 0, 11703.761],
  ["OECD (Jones et al. 2023)", 2021, 0, 0],
  ["Oceania (GCP)", 2021, 0, 434.682],
  ["Panama Canal Zone (Jones et al. 2023)", 2021, 0, 0],
  ["Puerto Rico", 2021, 0, 0],
  ["Ryukyu Islands (Jones et al. 2023)", 2021, 0, 0],
  ["Saint Martin (French part)", 2021, 0, 0],
  ["South America (GCP)", 2021, 0, 1074.998],
  ["St. Kitts-Nevis-Anguilla (Jones et al. 2023)", 2021, 0, 0],
  ["Svalbard and Jan Mayen", 2021, 0, 0],
  ["United States Virgin Islands", 2021, 0, 0],
  ["Western Sahara", 2021, 0, 0],
];

function componentToHex(c) {
  var hex = c.toString(16);
  return hex.length == 1 ? "0" + hex : hex;
}

function getCol(name) {
  max = 11472;
  min = 0;
  co2 = 0;
  for (var i = 0; i < countriesData.length; i++) {
    if (countriesData[i][0] == name) {
      co2 = countriesData[i][3];
    }
  }

  console.log(co2);

  co2Percent = (co2 - min) / (max - min);
  r = 255 * co2Percent;
  console.log("#" + componentToHex(Math.round(r)) + "0000");
  return "#" + componentToHex(Math.round(r)) + "0000";
}

function getDesc(name) {
  co2 = 0;
  for (var i = 0; i < countriesData.length; i++) {
    if (countriesData[i][0] == name) {
      co2 = countriesData[i][3];
    }
  }
  return co2 + " million tonnes";
}

var simplemaps_worldmap_mapdata = {
  main_settings: {
    //General settings
    width: "responsive", //'700' or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    popups: "detect",

    //State defaults
    state_description: "State description",
    state_color: "#88A4BC",
    state_hover_color: "#DED2D2",
    state_url: "http://simplemaps.com",
    border_size: 1.5,
    all_states_inactive: "no",
    all_states_zoomable: "yes",

    //Location defaults
    location_description: "Location description",
    location_color: "#FF0067",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 25,
    location_type: "square",
    location_image_source: "frog.png",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",

    //Label defaults
    label_color: "#d5ddec",
    label_hover_color: "#d5ddec",
    label_size: 22,
    label_font: "Arial",
    hide_labels: "no",

    //Zoom settings
    zoom: "yes",
    back_image: "no",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,

    //Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",

    //Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "no",
    images_directory: "default",
    fade_time: 0.1,
    link_text: "View Website",
    state_image_url: "",
    state_image_position: "",
    location_image_url: "",
  },
  state_specific: {
    AF: {
      name: "Afghanistan",
      description: getDesc("Afghanistan"),
      color: getCol("Afghanistan"),
    },
    AO: {
      name: "Angola",
      description: getDesc("Angola"),
      color: getCol("Angola"),
    },
    AL: {
      name: "Albania",
      description: getDesc("Albania"),
      color: getCol("Albania"),
    },
    AE: {
      name: "United Arab Emirates",
      description: getDesc("United Arab Emirates"),
      color: getCol("United Arab Emirates"),
    },
    AR: {
      name: "Argentina",
      description: getDesc("Argentina"),
      color: getCol("Argentina"),
    },
    AM: {
      name: "Armenia",
      description: getDesc("Armenia"),
      color: getCol("Armenia"),
    },
    AU: {
      name: "Australia",
      description: getDesc("Australia"),
      color: getCol("Australia"),
    },
    AT: {
      name: "Austria",
      description: getDesc("Austria"),
      color: getCol("Albania"),
    },
    AZ: {
      name: "Azerbaijan",
      description: getDesc("Azerbaijan"),
      color: getCol("Azerbaijan"),
    },
    BI: {
      name: "Burundi",
      description: getDesc("Burundi"),
      color: getCol("Burundi"),
    },
    BE: {
      name: "Belgium",
      description: getDesc("Belgium"),
      color: getCol("Belgium"),
    },
    BJ: {
      name: "Benin",
      description: getDesc("Benin"),
      color: getCol("Benin"),
    },
    BF: {
      name: "Burkina Faso",
      description: getDesc("Burkina Faso"),
      color: getCol("Burkina Faso"),
    },
    BD: {
      name: "Bangladesh",
      description: getDesc("Bangladesh"),
      color: getCol("Bangladesh"),
    },
    BG: {
      name: "Bulgaria",
      description: getDesc("Bulgaria"),
      color: getCol("Bulgaria"),
    },
    BH: {
      name: "Bahrain",
      description: getDesc("Bahrain"),
      color: getCol("Bahrain"),
    },
    BA: {
      name: "Bosnia and Herzegovina",
      description: getDesc("Bosnia and Herzegovina"),
      color: getCol("Bosnia and Herzegovina"),
    },
    BY: {
      name: "Belarus",
      description: getDesc("Belarus"),
      color: getCol("Belarus"),
    },
    BZ: {
      name: "Belize",
      description: getDesc("Belize"),
      color: getCol("Belize"),
    },
    BO: {
      name: "Bolivia",
      description: getDesc("Bolivia"),
      color: getCol("Bolivia"),
    },
    BR: {
      name: "Brazil",
      description: getDesc("Brazil"),
      color: getCol("Brazil"),
    },
    BN: {
      name: "Brunei Darussalam",
      description: getDesc("Brunei Darussalam"),
      color: getCol("Brunei Darussalam"),
    },
    BT: {
      name: "Bhutan",
      description: getDesc("Bhutan"),
      color: getCol("Bhutan"),
    },
    BW: {
      name: "Botswana",
      description: getDesc("Bhutan"),
      color: getCol("Bhutan"),
    },
    CF: {
      name: "Central African Republic",
      description: getDesc("Central African Republic"),
      color: getCol("Central African Republic"),
    },
    CA: {
      name: "Canada",
      description: getDesc("Canada"),
      color: getCol("Canada"),
    },
    CH: {
      name: "Switzerland",
      description: getDesc("Switzerland"),
      color: getCol("Switzerland"),
    },
    CL: {
      name: "Chile",
      description: getDesc("Chile"),
      color: getCol("Chile"),
    },
    CN: {
      color: getCol("China"),
      description: getDesc("China"),
      color: getCol("China"),
    },
    CI: {
      name: "Côte d'Ivoire",
      description: getDesc("Côte d'Ivoire"),
      color: getCol("Côte d'Ivoire"),
    },
    CM: {
      name: "Cameroon",
      description: getDesc("Cameroon"),
      color: getCol("Cameroon"),
    },
    CD: {
      name: "Democratic Republic of the Congo",
      description: getDesc("Democratic Republic of the Congo"),
      color: getCol("Democratic Republic of the Congo"),
    },
    CG: {
      name: "Republic of Congo",
      description: getDesc("Republic of Congo"),
      color: getCol("Republic of Congo"),
    },
    CO: {
      name: "Colombia",
      description: getDesc("Colombia"),
      color: getCol("Colombia"),
    },
    CR: {
      name: "Costa Rica",
      description: getDesc("Costa Rica"),
      color: getCol("Costa Rica"),
    },
    CU: {
      name: "Cuba",
      description: getDesc("Cuba"),
      color: getCol("Cuba"),
    },
    CZ: {
      name: "Czech Republic",
      description: getDesc("Czech Republic"),
      color: getCol("Czech Republic"),
    },
    DE: {
      name: "Germany",
      description: getDesc("Germany"),
      color: getCol("Germany"),
    },
    DJ: {
      name: "Djibouti",
      description: getDesc("Djibouti"),
      color: getCol("Djibouti"),
    },
    DK: {
      name: "Denmark",
      description: getDesc("Denmark"),
      color: getCol("Denmark"),
    },
    DO: {
      name: "Dominican Republic",
      description: getDesc("Dominican Republic"),
      color: getCol("Dominican Republic"),
    },
    DZ: {
      name: "Algeria",
      description: getDesc("Algeria"),
      color: getCol("Algeria"),
    },
    EC: {
      name: "Ecuador",
      description: getDesc("Ecuador"),
      color: getCol("Ecuador"),
    },
    EG: {
      name: "Egypt",
      description: getDesc("Egypt"),
      color: getCol("Egypt"),
    },
    ER: {
      name: "Eritrea",
      description: getDesc("Eritrea"),
      color: getCol("Eritrea"),
    },
    EE: {
      name: "Estonia",
      description: getDesc("Estonia"),
      color: getCol("Estonia"),
    },
    ET: {
      name: "Ethiopia",
      description: getDesc("Ethiopia"),
      color: getCol("Ethiopia"),
    },
    FI: {
      name: "Finland",
      description: getDesc("Finland"),
      color: getCol("Finland"),
    },
    FJ: {
      name: "Fiji",
      description: getDesc("Fiji"),
      color: getCol("Fiji"),
    },
    GA: {
      name: "Gabon",
      description: getDesc("Gabon"),
      color: getCol("Gabon"),
    },
    GB: {
      name: "United Kingdom",
      description: getDesc("United Kingdom"),
      color: getCol("United Kingdom"),
    },
    GE: {
      name: "Georgia",
      description: getDesc("Georgia"),
      color: getCol("Georgia"),
    },
    GH: {
      name: "Ghana",
      description: getDesc("Ghana"),
      color: getCol("Ghana"),
    },
    GN: {
      name: "Guinea",
      description: getDesc("Guinea"),
      color: getCol("Guinea"),
    },
    GM: {
      name: "The Gambia",
      description: getDesc("The Gambia"),
      color: getCol("The Gambia"),
    },
    GW: {
      name: "Guinea-Bissau",
      description: getDesc("Guinea-Bissau"),
      color: getCol("Guinea-Bissau"),
    },
    GQ: {
      name: "Equatorial Guinea",
      description: getDesc("Equatorial Guinea"),
      color: getCol("Equatorial Guinea"),
    },
    GR: {
      name: "Greece",
      description: getDesc("Greece"),
      color: getCol("Greece"),
    },
    GL: {
      name: "Greenland",
      description: getDesc("Greenland"),
      color: getCol("Greenland"),
    },
    GT: {
      name: "Guatemala",
      description: getDesc("Guatemala"),
      color: getCol("Guatemala"),
    },
    GY: {
      name: "Guyana",
      description: getDesc("Guyana"),
      color: getCol("Guyana"),
    },
    HN: {
      name: "Honduras",
      description: getDesc("Honduras"),
      color: getCol("Honduras"),
    },
    HR: {
      name: "Croatia",
      description: getDesc("Croatia"),
      color: getCol("Croatia"),
    },
    HT: {
      name: "Haiti",
      description: getDesc("Haiti"),
      color: getCol("Haiti"),
    },
    HU: {
      name: "Hungary",
      description: getDesc("Hungary"),
      color: getCol("Hungary"),
    },
    ID: {
      name: "Indonesia",
      description: getDesc("Indonesia"),
      color: getCol("Indonesia"),
    },
    IN: {
      name: "India",
      description: getDesc("India"),
      color: getCol("India"),
    },
    IE: {
      name: "Ireland",
      description: getDesc("Ireland"),
      color: getCol("Ireland"),
    },
    IR: {
      name: "c",
      description: getDesc("Ireland"),
      color: getCol("Ireland"),
    },
    IQ: {
      name: "Iraq",
      description: getDesc("Iraq"),
      color: getCol("Iraq"),
    },
    IS: {
      name: "Iceland",
      description: getDesc("Iceland"),
      color: getCol("Iceland"),
    },
    IL: {
      name: "Israel",
      description: getDesc("Israel"),
      color: getCol("Israel"),
    },
    IT: {
      name: "Italy",
      description: getDesc("Italy"),
      color: getCol("Italy"),
    },
    JM: {
      name: "Jamaica",
      description: getDesc("Jamaica"),
      color: getCol("Jamaica"),
    },
    JO: {
      name: "Jordan",
      description: getDesc("Jordan"),
      color: getCol("Jordan"),
    },
    JP: {
      name: "Japan",
      description: getDesc("Japan"),
      color: getCol("Japan"),
    },
    KZ: {
      name: "Kazakhstan",
      description: getDesc("Kazakhstan"),
      color: getCol("Kazakhstan"),
    },
    KE: {
      name: "Kenya",
      description: getDesc("Kenya"),
      color: getCol("Kenya"),
    },
    KG: {
      name: "Kyrgyzstan",
      description: getDesc("Kyrgyzstan"),
      color: getCol("Kyrgyzstan"),
    },
    KH: {
      name: "Cambodia",
      description: getDesc("Cambodia"),
      color: getCol("Cambodia"),
    },
    KR: {
      name: "Republic of Korea",
      description: getDesc("Republic of Korea"),
      color: getCol("Republic of Korea"),
    },
    XK: {
      name: "Kosovo",
      description: getDesc("Kosovo"),
      color: getCol("Kosovo"),
    },
    KW: {
      name: "Kuwait",
      description: getDesc("Kuwait"),
      color: getCol("Kuwait"),
    },
    LA: {
      name: "Lao PDR",
      description: getDesc("Lao PDR"),
      color: getCol("Lao PDR"),
    },
    LB: {
      name: "Lebanon",
      description: getDesc("Lebanon"),
      color: getCol("Lebanon"),
    },
    LR: {
      name: "Liberia",
      description: getDesc("Liberia"),
      color: getCol("Liberia"),
    },
    LY: {
      name: "Libya",
      description: getDesc("Libya"),
      color: getCol("Libya"),
    },
    LK: {
      name: "Sri Lanka",
      description: getDesc("Sri Lanka"),
      color: getCol("Sri Lanka"),
    },
    LS: {
      name: "Lesotho",
      description: getDesc("Lesotho"),
      color: getCol("Lesotho"),
    },
    LT: {
      name: "Lithuania",
      description: getDesc("Lithuania"),
      color: getCol("Lithuania"),
    },
    LU: {
      name: "Luxembourg",
      description: getDesc("Luxembourg"),
      color: getCol("Luxembourg"),
    },
    LV: {
      name: "Latvia",
      description: getDesc("Latvia"),
      color: getCol("Latvia"),
    },
    MA: {
      name: "Morocco",
      description: getDesc("Morocco"),
      color: getCol("Morocco"),
    },
    MD: {
      name: "Moldova",
      description: getDesc("Moldova"),
      color: getCol("Moldova"),
    },
    MG: {
      name: "Madagascar",
      description: getDesc("Madagascar"),
      color: getCol("Madagascar"),
    },
    MX: {
      name: "Mexico",
      description: getDesc("Mexico"),
      color: getCol("Mexico"),
    },
    MK: {
      name: "Macedonia",
      description: getDesc("Macedonia"),
      color: getCol("Macedonia"),
    },
    ML: {
      name: "Mali",
      description: getDesc("Mali"),
      color: getCol("Mali"),
    },
    MM: {
      name: "Myanmar",
      description: getDesc("Myanmar"),
      color: getCol("Myanmar"),
    },
    ME: {
      name: "Montenegro",
      description: getDesc("Montenegro"),
      color: getCol("Montenegro"),
    },
    MN: {
      name: "Mongolia",
      description: getDesc("Mongolia"),
      color: getCol("Mongolia"),
    },
    MZ: {
      name: "Mozambique",
      description: getDesc("Mozambique"),
      color: getCol("Mozambique"),
    },
    MR: {
      name: "Mauritania",
      description: getDesc("Mauritania"),
      color: getCol("Mauritania"),
    },
    MW: {
      name: "Malawi",
      description: getDesc("Malawi"),
      color: getCol("Malawi"),
    },
    MY: {
      name: "Malaysia",
      description: getDesc("Malaysia"),
      color: getCol("Malaysia"),
    },
    NA: {
      name: "Namibia",
      description: getDesc("Namibia"),
      color: getCol("Namibia"),
    },
    NE: {
      name: "Niger",
      description: getDesc("Niger"),
      color: getCol("Niger"),
    },
    NG: {
      name: "Nigeria",
      description: getDesc("Nigeria"),
      color: getCol("Nigeria"),
    },
    NI: {
      name: "Nicaragua",
      description: getDesc("Nicaragua"),
      color: getCol("Nicaragua"),
    },
    NL: {
      name: "Netherlands",
      description: getDesc("Netherlands"),
      color: getCol("Netherlands"),
    },
    NO: {
      name: "Norway",
      description: getDesc("Norway"),
      color: getCol("Norway"),
    },
    NP: {
      name: "Nepal",
      description: getDesc("Nepal"),
      color: getCol("Nepal"),
    },
    NZ: {
      name: "New Zealand",
      description: getDesc("Belarus"),
      color: getCol("Belarus"),
    },
    OM: {
      name: "Oman",
      description: getDesc("Oman"),
      color: getCol("Oman"),
    },
    PK: {
      name: "Pakistan",
      description: getDesc("Pakistan"),
      color: getCol("Pakistan"),
    },
    PA: {
      name: "Panama",
      description: getDesc("Panama"),
      color: getCol("Panama"),
    },
    PE: {
      name: "Peru",
      description: getDesc("Peru"),
      color: getCol("Peru"),
    },
    PH: {
      name: "Philippines",
      description: getDesc("Philippines"),
      color: getCol("Philippines"),
    },
    PG: {
      name: "Papua New Guinea",
      description: getDesc("Papua New Guinea"),
      color: getCol("Papua New Guinea"),
    },
    PL: {
      name: "Poland",
      description: getDesc("Poland"),
      color: getCol("Poland"),
    },
    KP: {
      name: "Dem. Rep. Korea",
      description: getDesc("Dem. Rep. Korea"),
      color: getCol("Dem. Rep. Korea"),
    },
    PT: {
      name: "Portugal",
      description: getDesc("Portugal"),
      color: getCol("Portugal"),
    },
    PY: {
      name: "Paraguay",
      description: getDesc("Paraguay"),
      color: getCol("Paraguay"),
    },
    PS: {
      name: "Palestine",
      description: getDesc("Palestine"),
      color: getCol("Palestine"),
    },
    QA: {
      name: "Qatar",
      description: getDesc("Qatar"),
      color: getCol("Qatar"),
    },
    RO: {
      name: "Romania",
      description: getDesc("Romania"),
      color: getCol("Romania"),
    },
    RU: {
      name: "Russia",
      description: getDesc("Russia"),
      color: getCol("Russia"),
    },
    RW: {
      name: "Rwanda",
      description: getDesc("Rwanda"),
      color: getCol("Rwanda"),
    },
    EH: {
      name: "Western Sahara",
      description: getDesc("Western Sahara"),
      color: getCol("Western Sahara"),
    },
    SA: {
      name: "Saudi Arabia",
      description: getDesc("Saudi Arabia"),
      color: getCol("Saudi Arabia"),
    },
    SD: {
      name: "Sudan",
      description: getDesc("Sudan"),
      color: getCol("Sudan"),
    },
    SS: {
      name: "South Sudan",
      description: getDesc("South Sudan"),
      color: getCol("South Sudan"),
    },
    SN: {
      name: "Senegal",
      description: getDesc("Senegal"),
      color: getCol("Senegal"),
    },
    SL: {
      name: "Sierra Leone",
      description: getDesc("Sierra Leone"),
      color: getCol("Sierra Leone"),
    },
    SV: {
      name: "El Salvador",
      description: getDesc("El Salvador"),
      color: getCol("El Salvador"),
    },
    RS: {
      name: "Serbia",
      description: getDesc("Serbia"),
      color: getCol("Serbia"),
    },
    SR: {
      name: "Suriname",
      description: getDesc("Rwanda"),
      color: getCol("Rwanda"),
    },
    SK: {
      name: "Slovakia",
      description: getDesc("Slovakia"),
      color: getCol("Slovakia"),
    },
    SI: {
      name: "Slovenia",
      description: getDesc("Slovenia"),
      color: getCol("Slovenia"),
    },
    SE: {
      name: "Sweden",
      description: getDesc("Sweden"),
      color: getCol("Sweden"),
    },
    SZ: {
      name: "Swaziland",
      description: getDesc("Swaziland"),
      color: getCol("Swaziland"),
    },
    SY: {
      name: "Syria",
      description: getDesc("Syria"),
      color: getCol("Syria"),
    },
    TD: {
      name: "Chad",
      description: getDesc("Chad"),
      color: getCol("Chad"),
    },
    TG: {
      name: "Togo",
      description: getDesc("Togo"),
      color: getCol("Togo"),
    },
    TH: {
      name: "Thailand",
      description: getDesc("Thailand"),
      color: getCol("Thailand"),
    },
    TJ: {
      name: "Tajikistan",
      description: getDesc("Tajikistan"),
      color: getCol("Tajikistan"),
    },
    TM: {
      name: "Turkmenistan",
      description: getDesc("Rwanda"),
      color: getCol("Rwanda"),
    },
    TL: {
      name: "Timor-Leste",
      description: getDesc("Timor-Leste"),
      color: getCol("Timor-Leste"),
    },
    TN: {
      name: "Tunisia",
      description: getDesc("Tunisia"),
      color: getCol("Tunisia"),
    },
    TR: {
      name: "Turkey",
      description: getDesc("Turkey"),
      color: getCol("Turkey"),
    },
    TW: {
      name: "Taiwan",
      description: getDesc("Taiwan"),
      color: getCol("Taiwan"),
    },
    TZ: {
      name: "Tanzania",
      description: getDesc("Tanzania"),
      color: getCol("Tanzania"),
    },
    UG: {
      name: "Uganda",
      description: getDesc("Uganda"),
      color: getCol("Uganda"),
    },
    UA: {
      name: "Ukraine",
      description: getDesc("Ukraine"),
      color: getCol("Ukraine"),
    },
    UY: {
      name: "Uruguay",
      description: getDesc("Uruguay"),
      color: getCol("Uruguay"),
    },
    US: {
      name: "United States",
      description: getDesc("United States"),
      color: getCol("United States"),
    },
    UZ: {
      name: "Uzbekistan",
      description: getDesc("Uzbekistan"),
      color: getCol("Uzbekistan"),
    },
    VE: {
      name: "Venezuela",
      description: getDesc("Venezuela"),
      color: getCol("Venezuela"),
    },
    VN: {
      name: "Vietnam",
      description: getDesc("Vietnam"),
      color: getCol("Vietnam"),
    },
    VU: {
      name: "Vanuatu",
      description: getDesc("Vanuatu"),
      color: getCol("Vanuatu"),
    },
    YE: {
      name: "Yemen",
      description: getDesc("Yemen"),
      color: getCol("Yemen"),
    },
    ZA: {
      name: "South Africa",
      description: getDesc("South Africa"),
      color: getCol("South Africa"),
    },
    ZM: {
      name: "Zambia",
      description: getDesc("Zambia"),
      color: getCol("Zambia"),
    },
    ZW: {
      name: "Zimbabwe",
      description: getDesc("Zimbabwe"),
      color: getCol("Zimbabwe"),
    },
    SO: {
      name: "Somalia",
      description: getDesc("Somalia"),
      color: getCol("Somalia"),
    },
    GF: {
      name: "France",
      description: getDesc("France"),
      color: getCol("France"),
    },
    FR: {
      name: "France",
      description: getDesc("France"),
      color: getCol("France"),
    },
    ES: {
      name: "Spain",
      description: getDesc("Spain"),
      color: getCol("Spain"),
    },
    AW: {
      name: "Aruba",
      description: getDesc("Aruba"),
      color: getCol("Aruba"),
    },
    AI: {
      name: "Anguilla",
      description: getDesc("Anguilla"),
      color: getCol("Anguilla"),
    },
    AD: {
      name: "Andorra",
      description: getDesc("Andorra"),
      color: getCol("Andorra"),
    },
    AG: {
      name: "Antigua and Barbuda",
      description: getDesc("Antigua and Barbuda"),
      color: getCol("Antigua and Barbuda"),
    },
    BS: {
      name: "Bahamas",
      description: getDesc("Bahamas"),
      color: getCol("Bahamas"),
    },
    BM: {
      name: "Bermuda",
      description: getDesc("Bermuda"),
      color: getCol("Bermuda"),
    },
    BB: {
      name: "Barbados",
      description: getDesc("Barbados"),
      color: getCol("Barbados"),
    },
    KM: {
      name: "Comoros",
      description: getDesc("Comoros"),
      color: getCol("Comoros"),
    },
    CV: {
      name: "Cape Verde",
      description: getDesc("Cape Verde"),
      color: getCol("Cape Verde"),
    },
    KY: {
      name: "Cayman Islands",
      description: getDesc("Cayman Islands"),
      color: getCol("Cayman Islands"),
    },
    DM: {
      name: "Dominica",
      description: getDesc("Dominica"),
      color: getCol("Dominica"),
    },
    FK: {
      name: "Falkland Islands",
      description: getDesc("Falkland Islands"),
      color: getCol("Falkland Islands"),
    },
    FO: {
      name: "Faeroe Islands",
      description: getDesc("Faeroe Islands"),
      color: getCol("Faeroe Islands"),
    },
    GD: {
      name: "Grenada",
      description: getDesc("Grenada"),
      color: getCol("Grenada"),
    },
    HK: {
      name: "Hong Kong",
      description: getDesc("Hong Kong"),
      color: getCol("Hong Kong"),
    },
    KN: {
      name: "Saint Kitts and Nevis",
      description: getDesc("Saint Kitts and Nevis"),
      color: getCol("Saint Kitts and Nevis"),
    },
    LC: {
      name: "Saint Lucia",
      description: getDesc("Saint Lucia"),
      color: getCol("Saint Lucia"),
    },
    LI: {
      name: "Liechtenstein",
      description: getDesc("Liechtenstein"),
      color: getCol("Liechtenstein"),
    },
    MF: {
      name: "Saint Martin (French)",
      description: getDesc("Saint Martin (French)"),
      color: getCol("Saint Martin (French)"),
    },
    MV: {
      name: "Maldives",
      description: getDesc("Maldives"),
      color: getCol("Maldives"),
    },
    MT: {
      name: "Malta",
      description: getDesc("Malta"),
      color: getCol("Malta"),
    },
    MS: {
      name: "Montserrat",
      description: getDesc("Montserrat"),
      color: getCol("Montserrat"),
    },
    MU: {
      name: "Mauritius",
      description: getDesc("Mauritius"),
      color: getCol("Mauritius"),
    },
    NC: {
      name: "New Caledonia",
      description: getDesc("New Caledonia"),
      color: getCol("New Caledonia"),
    },
    NR: {
      name: "Nauru",
      description: getDesc("Nauru"),
      color: getCol("Nauru"),
    },
    PN: {
      name: "Pitcairn Islands",
      description: getDesc("Pitcairn Islands"),
      color: getCol("Pitcairn Islands"),
    },
    PR: {
      name: "Puerto Rico",
      description: getDesc("Puerto Rico"),
      color: getCol("Puerto Rico"),
    },
    PF: {
      name: "French Polynesia",
      description: getDesc("French Polynesia"),
      color: getCol("French Polynesia"),
    },
    SG: {
      name: "Singapore",
      description: getDesc("Singapore"),
      color: getCol("Singapore"),
    },
    SB: {
      name: "Solomon Islands",
      description: getDesc("Solomon Islands"),
      color: getCol("Solomon Islands"),
    },
    ST: {
      name: "São Tomé and Principe",
      description: getDesc("São Tomé and Principe"),
      color: getCol("São Tomé and Principe"),
    },
    SX: {
      name: "Saint Martin (Dutch)",
      description: getDesc("Saint Martin (Dutch)"),
      color: getCol("Saint Martin (Dutch)"),
    },
    SC: {
      name: "Seychelles",
      description: getDesc("Seychelles"),
      color: getCol("Seychelles"),
    },
    TC: {
      name: "Turks and Caicos Islands",
      description: getDesc("Turks and Caicos Islands"),
      color: getCol("Turks and Caicos Islands"),
    },
    TO: {
      name: "Tonga",
      description: getDesc("Tonga"),
      color: getCol("Tonga"),
    },
    TT: {
      name: "Trinidad and Tobago",
      description: " ",
      description: getDesc("Trinidad and Tobago"),
      color: getCol("Trinidad and Tobago"),
    },
    VC: {
      name: "Saint Vincent and the Grenadines",
      description: getDesc("Saint Vincent and the Grenadines"),
      color: getCol("Saint Vincent and the Grenadines"),
    },
    VG: {
      name: "British Virgin Islands",
      description: getDesc("British Virgin Islands"),
      color: getCol("British Virgin Islands"),
    },
    VI: {
      name: "United States Virgin Islands",
      description: getDesc("United States Virgin Islands"),
      color: getCol("United States Virgin Islands"),
    },
    CY: {
      name: "Cyprus",
      description: getDesc("Cyprus"),
      color: getCol("Cyprus"),
    },
    RE: {
      name: "Reunion (France)",
      description: getDesc("Reunion (France)"),
      color: getCol("Reunion (France)"),
    },
    YT: {
      name: "Mayotte (France)",
      description: getDesc("Mayotte (France)"),
      color: getCol("Mayotte (France)"),
    },
    MQ: {
      name: "Martinique (France)",
      description: getDesc("Martinique (France)"),
      color: getCol("Martinique (France)"),
    },
    GP: {
      name: "Guadeloupe (France)",
      description: getDesc("Guadeloupe (France)"),
      color: getCol("Guadeloupe (France)"),
    },
    CW: {
      name: "Curaco (Netherlands)",
      description: getDesc("Curaco (Netherlands)"),
      color: getCol("Curaco (Netherlands)"),
    },
    IC: {
      name: "Canary Islands (Spain)",
      description: getDesc("Canary Islands (Spain)"),
      color: getCol("Canary Islands (Spain)"),
    },
  },
  locations: {},
  labels: {},
  legend: {
    entries: [],
  },
  regions: {},
  data: {
    data: {
      CN: "30.903",
      US: "13.488",
      IN: "7.299",
      RU: "4.729",
      JP: "2.875",
      IR: "2.017",
      DE: "1.818",
      SA: "1.811",
      ID: "1.668",
      KR: "1.66",
    },
  },
};
